version: '3'

services:
  icon-manager:
    build: .
    container_name: icon-manager
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./static/icons:/app/static/icons
    environment:
      - SECRET_KEY=icon_manager_secret_key_change_this_in_production
      - ICON_STORAGE_PATH=/app/static/icons
      - FLASK_ENV=production
